spring:
  datasource:
    url: jdbc:h2:~/batch;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap

file:
  path: /Users/jaquelaurenti/Desktop/Exclusao/teste.txt
  input: classpath:pessoas.txt